### ISSUE TITLE
Typo  (#txp-write-sort-groups)

### ISSUE THREAD

**Issue by phiw13** [Bloke/smd_article_stats#1]
Typo [here](https://github.com/Bloke/smd_article_stats/blob/master/smd_article_stats.php#L215)

`#txp-write-sort-groups` should be `#txp-write-sort-group`

also: the text filter  group (#txp-textfilter-group) is gone on TXP 4.7

**Comment by phiw13** [comment]
And also - consider adding the option to insert the widget **after** the Sort group

**Comment by Bloke** [comment]
Fixed in 76b3771b.
